"""
StackRadar — Learning Resource Discovery.

Finds the best videos, playlists and courses for a tracked technology.

DESIGN RULE (non-negotiable): every link this module emits is either
  (a) returned by the YouTube Data API with live statistics attached, or
  (b) a curated *deep-link* into a search/listing page on a stable platform
      (docs.rs, DevDocs, freeCodeCamp, NPTEL...) that cannot 404.

Nothing here is generated by a language model. An LLM asked for "the best React
playlist" will happily invent a video id — it is the right shape, it looks
plausible, and it goes to a dead page. That is the same failure mode as the
fabricated `random.uniform()` score history this project already removed, except
the user sees it directly. If we cannot verify a link exists, we do not ship it.

Degrades cleanly: with no YOUTUBE_API_KEY the module still returns the curated
platform set plus scoped YouTube search links, so the feature is useful on a
fresh clone with an empty .env.
"""

from __future__ import annotations

import re
import math
import asyncio
from datetime import datetime, timezone, timedelta
from typing import Any, Optional

import httpx
from loguru import logger

from app.core.config import settings

YOUTUBE_API = "https://www.googleapis.com/youtube/v3"

# How many API results to consider before ranking. search.list costs 100 quota
# units regardless of maxResults, so we take the maximum and rank generously.
SEARCH_POOL = 25

# Channels with a strong track record of long-form, project-based teaching.
# Used only as a small ranking nudge — never as a filter, so good work from
# unknown channels can still surface.
TRUSTED_CHANNELS = {
    "freecodecamp.org", "traversy media", "the net ninja", "fireship",
    "academind", "programming with mosh", "corey schafer", "tech with tim",
    "sentdex", "arjancodes", "theo - t3.gg", "web dev simplified",
    "codewithharry", "apna college", "telusko", "code with harry",
    "nptel-noc iitm", "gate smashers", "kunal kushwaha", "hitesh choudhary",
    "chai aur code", "love babbar", "striver", "take u forward",
}

# Hindi-first channels. India is StackRadar's primary market and a large share
# of learners prefer Hindi explanation over English for first-pass learning —
# this is surfaced as an explicit language toggle rather than mixed into one list.
HINDI_CHANNELS = {
    "codewithharry", "code with harry", "apna college", "telusko",
    "love babbar", "chai aur code", "gate smashers", "cs geeks",
}


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

_ISO_DUR = re.compile(r"P(?:(\d+)D)?T?(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?")


def _parse_duration(iso: str) -> Optional[int]:
    """ISO-8601 duration ('PT1H23M45S') -> seconds."""
    if not iso:
        return None
    m = _ISO_DUR.fullmatch(iso)
    if not m:
        return None
    d, h, mi, s = (int(x) if x else 0 for x in m.groups())
    return d * 86400 + h * 3600 + mi * 60 + s


def _parse_ts(raw: str) -> Optional[datetime]:
    if not raw:
        return None
    try:
        return datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError:
        return None


def _norm_log(val: float, floor: float, ceil: float) -> float:
    """Log-normalise into 0..1. Mirrors scoring._norm_log so both engines agree."""
    if val <= floor:
        return 0.0
    lo, hi = math.log(floor), math.log(ceil)
    return max(0.0, min(1.0, (math.log(val) - lo) / (hi - lo)))


# ─────────────────────────────────────────────────────────────────────────────
# Ranking
# ─────────────────────────────────────────────────────────────────────────────

def rank_resource(item: dict[str, Any], release_at: Optional[datetime] = None) -> float:
    """Score a candidate 0-100. Deliberately transparent — every term is
    explainable to a user who asks "why is this first?".

    Reach (35)       — log-scaled view count. A tutorial nobody watched is a
                       weak signal; a 4M-view one is a strong one. Log-scaled so
                       one viral video can't dominate a whole category.
    Engagement (25)  — likes/views. Separates "clicked" from "actually helped".
                       ~4% is excellent on educational content.
    Freshness (25)   — exponential decay on age, with a hard penalty if the
                       video predates the tool's current major release.
    Depth (15)       — a 12-minute overview and a 6-hour course serve different
                       needs; both beat a 90-second clip for learning.
    """
    views = item.get("views") or 0
    likes = item.get("likes") or 0
    published = item.get("published_at")
    duration = item.get("duration_s") or 0
    items_n = item.get("item_count") or 0
    channel = (item.get("channel") or "").strip().lower()

    reach = _norm_log(views, 2_000, 5_000_000) * 35.0

    ratio = (likes / views) if views > 500 else 0.0
    engagement = min(1.0, ratio / 0.05) * 25.0

    freshness = 0.0
    if published:
        age_days = (datetime.now(timezone.utc) - published).days
        # Half-life of ~18 months: teaching ages, but a great 2-year-old course
        # is still worth more than a mediocre new one.
        freshness = math.exp(-age_days / 780.0) * 25.0
        if release_at and published < release_at - timedelta(days=365):
            # Predates the current major release by over a year — likely teaches
            # a superseded API. Halve, don't exclude: fundamentals still hold.
            freshness *= 0.5

    if items_n:                       # playlist: depth is course length
        depth = min(1.0, items_n / 30.0) * 15.0
    elif duration:
        depth = min(1.0, duration / 5400.0) * 15.0   # saturates at 90 min
    else:
        depth = 0.0

    score = reach + engagement + freshness + depth
    if channel in TRUSTED_CHANNELS:
        score *= 1.08                 # small nudge, never a gate

    return round(min(100.0, score), 2)


def staleness(published: Optional[datetime], release_at: Optional[datetime],
              version: Optional[str]) -> Optional[str]:
    """Human-readable warning when a tutorial predates the current release.

    This is the piece no other resource list has: StackRadar already tracks
    every tool's live release data, so it can tell a learner *before* they
    invest six hours that the course was recorded two majors ago.
    """
    if not published or not release_at:
        return None
    gap = (release_at - published).days
    if gap < 365:
        return None
    years = gap / 365.0
    v = f" (current {version})" if version else ""
    return f"Recorded ~{years:.0f} year{'s' if years >= 1.5 else ''} before the current release{v}"


# ─────────────────────────────────────────────────────────────────────────────
# YouTube Data API
# ─────────────────────────────────────────────────────────────────────────────

async def _yt_get(client: httpx.AsyncClient, path: str, params: dict) -> Optional[dict]:
    params = {**params, "key": settings.YOUTUBE_API_KEY}
    try:
        r = await client.get(f"{YOUTUBE_API}/{path}", params=params, timeout=20)
        if r.status_code == 403:
            # Quota exhausted or key restricted. Not fatal — callers fall back
            # to curated links for the rest of the cycle.
            logger.warning(f"YouTube API 403 on {path} — quota or key restriction")
            return None
        r.raise_for_status()
        return r.json()
    except Exception as e:                                    # noqa: BLE001
        logger.warning(f"YouTube API {path} failed: {e}")
        return None


async def fetch_youtube(
    tool_name: str,
    *,
    language: str = "en",
    release_at: Optional[datetime] = None,
    limit: int = 6,
) -> list[dict[str, Any]]:
    """Search YouTube for tutorials/courses on `tool_name`, hydrate real stats,
    rank, and return the top `limit`. Empty list if no key or the API fails."""
    if not settings.YOUTUBE_API_KEY:
        return []

    query = f"{tool_name} tutorial" if language == "en" else f"{tool_name} tutorial hindi"

    async with httpx.AsyncClient(follow_redirects=True) as client:
        search = await _yt_get(client, "search", {
            "part": "snippet",
            "q": query,
            "type": "video,playlist",
            "maxResults": SEARCH_POOL,
            "order": "relevance",
            "relevanceLanguage": "hi" if language == "hi" else "en",
            "safeSearch": "strict",
            "videoEmbeddable": "any",
        })
        if not search:
            return []

        video_ids, playlist_ids, meta = [], [], {}
        for it in search.get("items", []):
            kind = it.get("id", {}).get("kind", "")
            sn = it.get("snippet", {})
            if kind.endswith("video"):
                vid = it["id"].get("videoId")
                if not vid:
                    continue
                video_ids.append(vid)
                key = ("video", vid)
            elif kind.endswith("playlist"):
                pid = it["id"].get("playlistId")
                if not pid:
                    continue
                playlist_ids.append(pid)
                key = ("playlist", pid)
            else:
                continue

            thumbs = sn.get("thumbnails", {})
            meta[key] = {
                "title": sn.get("title", ""),
                "channel": sn.get("channelTitle", ""),
                "blurb": (sn.get("description") or "")[:280],
                "thumbnail": (thumbs.get("medium") or thumbs.get("default") or {}).get("url"),
                "published_at": _parse_ts(sn.get("publishedAt", "")),
            }

        # Hydrate real statistics. search.list does NOT return view counts —
        # ranking on relevance alone would just mirror YouTube's own ordering.
        stats_calls = []
        if video_ids:
            stats_calls.append(_yt_get(client, "videos", {
                "part": "statistics,contentDetails",
                "id": ",".join(video_ids[:50]),
            }))
        if playlist_ids:
            stats_calls.append(_yt_get(client, "playlists", {
                "part": "contentDetails",
                "id": ",".join(playlist_ids[:50]),
            }))
        results = await asyncio.gather(*stats_calls) if stats_calls else []

    for payload in results:
        if not payload:
            continue
        for it in payload.get("items", []):
            iid = it.get("id")
            st = it.get("statistics", {}) or {}
            cd = it.get("contentDetails", {}) or {}
            for key in (("video", iid), ("playlist", iid)):
                if key in meta:
                    if "itemCount" in cd:
                        meta[key]["item_count"] = int(cd["itemCount"])
                    if "duration" in cd:
                        meta[key]["duration_s"] = _parse_duration(cd["duration"])
                    if "viewCount" in st:
                        meta[key]["views"] = int(st["viewCount"])
                    if "likeCount" in st:
                        meta[key]["likes"] = int(st["likeCount"])

    out = []
    for (kind, iid), m in meta.items():
        # Drop items the stats call never confirmed — if YouTube didn't return
        # a record for the id, we can't vouch for it.
        if kind == "video" and m.get("views") is None:
            continue
        if kind == "playlist" and m.get("item_count") is None:
            continue
        url = (f"https://www.youtube.com/watch?v={iid}" if kind == "video"
               else f"https://www.youtube.com/playlist?list={iid}")
        ch = (m.get("channel") or "").strip().lower()
        out.append({
            **m,
            "kind": kind,
            "source": "youtube",
            "url": url,
            "language": "hi" if ch in HINDI_CHANNELS else language,
            "rank_score": rank_resource(m, release_at),
            "staleness": staleness(m.get("published_at"), release_at, None),
        })

    out.sort(key=lambda r: r["rank_score"], reverse=True)
    return out[:limit]


# ─────────────────────────────────────────────────────────────────────────────
# Curated platforms (always valid, no key required)
# ─────────────────────────────────────────────────────────────────────────────

def curated_platforms(tool_name: str, slug: str, homepage: Optional[str] = None,
                      github_repo: Optional[str] = None) -> list[dict[str, Any]]:
    """Non-YouTube resources worth a learner's time.

    Every entry is a *deep-link into a search or listing page*, never a guessed
    article id — so these keep working as the platforms' own content changes,
    and none of them can rot into a 404.
    """
    q = tool_name.replace(" ", "+")
    out: list[dict[str, Any]] = []

    if homepage:
        out.append({
            "title": f"{tool_name} — official documentation",
            "url": homepage,
            "blurb": "The primary source. Usually the fastest path once you know the basics.",
            "channel": "Official",
        })

    out += [
        {
            "title": f"{tool_name} on DevDocs",
            "url": f"https://devdocs.io/#q={q}",
            "blurb": "Offline-capable API reference across 400+ technologies in one search box.",
            "channel": "DevDocs",
        },
        {
            "title": f"freeCodeCamp articles on {tool_name}",
            "url": f"https://www.freecodecamp.org/news/search?query={q}",
            "blurb": "Long-form, free, project-based written tutorials.",
            "channel": "freeCodeCamp",
        },
        {
            "title": f"Awesome {tool_name} lists",
            "url": f"https://github.com/search?q=awesome+{q}&type=repositories",
            "blurb": "Community-maintained collections of the best libraries, tools and guides.",
            "channel": "GitHub",
        },
        {
            "title": f"{tool_name} questions on Stack Overflow",
            "url": f"https://stackoverflow.com/questions/tagged/{slug}",
            "blurb": "What people actually get stuck on — good for spotting the sharp edges early.",
            "channel": "Stack Overflow",
        },
        # India-specific. NPTEL/SWAYAM certificates carry real weight with
        # Indian recruiters and the courses are free, which matters for the
        # student segment this product is aimed at.
        {
            "title": f"NPTEL / SWAYAM courses covering {tool_name}",
            "url": f"https://nptel.ac.in/courses?search={q}",
            "blurb": "Free IIT/IISc-taught courses with a recognised certificate on completion.",
            "channel": "NPTEL",
            "language": "en",
        },
    ]

    if github_repo:
        out.append({
            "title": f"{tool_name} source & issues",
            "url": f"https://github.com/{github_repo}",
            "blurb": "Reading real issues and PRs is the fastest way past intermediate.",
            "channel": "GitHub",
        })

    for r in out:
        r.setdefault("kind", "platform")
        r.setdefault("source", "curated")
        r.setdefault("language", "en")
        r.setdefault("rank_score", 0.0)
        r.setdefault("staleness", None)
        r.setdefault("thumbnail", None)
        r.setdefault("views", None)
        r.setdefault("likes", None)
        r.setdefault("duration_s", None)
        r.setdefault("item_count", None)
        r.setdefault("published_at", None)
    return out


def youtube_search_fallback(tool_name: str, language: str = "en") -> list[dict[str, Any]]:
    """Used when no API key is configured: scoped YouTube searches the user can
    run themselves. Honest about being a search, not a recommendation."""
    q = tool_name.replace(" ", "+")
    base = "https://www.youtube.com/results?search_query="

    if language == "hi":
        # Hindi learners search in Hinglish, so the queries are built that way
        # rather than being a transliteration of the English ones.
        specs = [
            (f"{tool_name} full course (Hindi)", f"{q}+full+course+hindi",
             "पूरा कोर्स — long-form Hindi courses on this technology."),
            (f"{tool_name} tutorial for beginners (Hindi)", f"{q}+tutorial+hindi+for+beginners",
             "Beginner-friendly Hindi explanation, good for a first pass."),
            (f"{tool_name} project (Hindi)", f"{q}+project+hindi",
             "Build-along projects explained in Hindi."),
            (f"{tool_name} interview questions (Hindi)", f"{q}+interview+questions+hindi",
             "What Indian interviewers actually ask on this stack."),
        ]
    else:
        specs = [
            (f"{tool_name} full course", f"{q}+full+course",
             "Long-form courses — sorted by YouTube relevance."),
            (f"{tool_name} crash course", f"{q}+crash+course",
             "Sub-2-hour overviews to decide if this is worth learning."),
            (f"{tool_name} project tutorial", f"{q}+project+tutorial",
             "Build-along videos — the fastest way to retain a new tool."),
            (f"{tool_name} interview questions", f"{q}+interview+questions",
             "What gets asked once you claim this on a CV."),
        ]

    return [{
        "title": t, "url": base + s, "blurb": b, "channel": "YouTube search",
        "kind": "search", "source": "curated", "language": language,
        "rank_score": 0.0, "staleness": None, "thumbnail": None, "views": None,
        "likes": None, "duration_s": None, "item_count": None, "published_at": None,
    } for t, s, b in specs]
