"""initial_schema_v1

Revision ID: 247f0a69e623
Revises: 
Create Date: 2026-05-09 01:48:15.699816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247f0a69e623'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domains_id'), 'domains', ['id'], unique=False)
    op.create_index(op.f('ix_domains_name'), 'domains', ['name'], unique=True)
    op.create_index(op.f('ix_domains_slug'), 'domains', ['slug'], unique=True)
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('github_repo', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('forks', sa.Integer(), nullable=True),
    sa.Column('open_issues', sa.Integer(), nullable=True),
    sa.Column('watchers', sa.Integer(), nullable=True),
    sa.Column('hn_count', sa.Integer(), nullable=True),
    sa.Column('devto_count', sa.Integer(), nullable=True),
    sa.Column('reddit_count', sa.Integer(), nullable=True),
    sa.Column('news_count', sa.Integer(), nullable=True),
    sa.Column('sentiment_positive', sa.Integer(), nullable=True),
    sa.Column('sentiment_negative', sa.Integer(), nullable=True),
    sa.Column('sentiment_label', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('growth_pct', sa.Float(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('trend_stage', sa.String(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('learning_priority', sa.String(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('parent_tool_id', sa.Integer(), nullable=True),
    sa.Column('is_entry_point', sa.Boolean(), nullable=True),
    sa.Column('learning_sequence_score', sa.Integer(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['parent_tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_category'), 'tools', ['category'], unique=False)
    op.create_index(op.f('ix_tools_id'), 'tools', ['id'], unique=False)
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=True)
    op.create_index(op.f('ix_tools_slug'), 'tools', ['slug'], unique=True)
    op.create_table('tool_roadmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('estimated_weeks', sa.Integer(), nullable=True),
    sa.Column('steps_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_roadmaps_id'), 'tool_roadmaps', ['id'], unique=False)
    op.create_index(op.f('ix_tool_roadmaps_slug'), 'tool_roadmaps', ['slug'], unique=True)
    op.create_table('tool_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('forks', sa.Integer(), nullable=True),
    sa.Column('mentions', sa.Integer(), nullable=True),
    sa.Column('hn_count', sa.Integer(), nullable=True),
    sa.Column('devto_count', sa.Integer(), nullable=True),
    sa.Column('reddit_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id', 'date', name='uq_tool_date')
    )
    op.create_index(op.f('ix_tool_snapshots_id'), 'tool_snapshots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_snapshots_id'), table_name='tool_snapshots')
    op.drop_table('tool_snapshots')
    op.drop_index(op.f('ix_tool_roadmaps_slug'), table_name='tool_roadmaps')
    op.drop_index(op.f('ix_tool_roadmaps_id'), table_name='tool_roadmaps')
    op.drop_table('tool_roadmaps')
    op.drop_index(op.f('ix_tools_slug'), table_name='tools')
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_index(op.f('ix_tools_id'), table_name='tools')
    op.drop_index(op.f('ix_tools_category'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_domains_slug'), table_name='domains')
    op.drop_index(op.f('ix_domains_name'), table_name='domains')
    op.drop_index(op.f('ix_domains_id'), table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
