"""Phase 6 Career Signal Engine Models

Revision ID: 4b1802786ed7
Revises: 6a84a0c4d944
Create Date: 2026-03-08 19:08:42.165069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1802786ed7'
down_revision: Union[str, None] = '6a84a0c4d944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technology_difficulty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technology_id')
    )
    op.create_index(op.f('ix_technology_difficulty_id'), 'technology_difficulty', ['id'], unique=False)
    op.create_table('technology_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_domains_domain'), 'technology_domains', ['domain'], unique=False)
    op.create_index(op.f('ix_technology_domains_id'), 'technology_domains', ['id'], unique=False)
    op.create_table('technology_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('prerequisite', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_prerequisites_id'), 'technology_prerequisites', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technology_prerequisites_id'), table_name='technology_prerequisites')
    op.drop_table('technology_prerequisites')
    op.drop_index(op.f('ix_technology_domains_id'), table_name='technology_domains')
    op.drop_index(op.f('ix_technology_domains_domain'), table_name='technology_domains')
    op.drop_table('technology_domains')
    op.drop_index(op.f('ix_technology_difficulty_id'), table_name='technology_difficulty')
    op.drop_table('technology_difficulty')
    # ### end Alembic commands ###
