"""Phase 5 Model updates

Revision ID: 6a84a0c4d944
Revises: b32aa0cfd5d3
Create Date: 2026-03-08 18:37:02.298005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a84a0c4d944'
down_revision: Union[str, None] = 'b32aa0cfd5d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('resource_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roadmap_steps_id'), 'roadmap_steps', ['id'], unique=False)
    op.add_column('technologies', sa.Column('category', sa.String(), nullable=True))
    op.add_column('technologies', sa.Column('github_count', sa.Integer(), nullable=True))
    op.add_column('technologies', sa.Column('hn_count', sa.Integer(), nullable=True))
    op.add_column('technologies', sa.Column('devto_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technologies', 'devto_count')
    op.drop_column('technologies', 'hn_count')
    op.drop_column('technologies', 'github_count')
    op.drop_column('technologies', 'category')
    op.drop_index(op.f('ix_roadmap_steps_id'), table_name='roadmap_steps')
    op.drop_table('roadmap_steps')
    # ### end Alembic commands ###
