"""Phase 7 Technology Roles and Stage

Revision ID: 9ca154882cbd
Revises: 4b1802786ed7
Create Date: 2026-03-08 20:07:12.061523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca154882cbd'
down_revision: Union[str, None] = '4b1802786ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technology_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_roles_id'), 'technology_roles', ['id'], unique=False)
    op.add_column('technologies', sa.Column('stage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technologies', 'stage')
    op.drop_index(op.f('ix_technology_roles_id'), table_name='technology_roles')
    op.drop_table('technology_roles')
    # ### end Alembic commands ###
