"""task_002_003

Revision ID: ef39c37c34f0
Revises: 247f0a69e623
Create Date: 2026-05-16 23:09:41.964679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef39c37c34f0'
down_revision: Union[str, None] = '247f0a69e623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_snapshots', sa.Column('recorded_at', sa.DateTime(), nullable=True))
    op.add_column('tool_snapshots', sa.Column('github_stars_delta', sa.Integer(), nullable=True))
    op.add_column('tool_snapshots', sa.Column('mention_count', sa.Integer(), nullable=True))
    op.add_column('tool_snapshots', sa.Column('sentiment_score', sa.Float(), nullable=True))
    op.drop_index('ix_tool_snapshots_id', table_name='tool_snapshots')
    op.drop_constraint('uq_tool_date', 'tool_snapshots', type_='unique')
    op.create_index(op.f('ix_tool_snapshots_recorded_at'), 'tool_snapshots', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_tool_snapshots_tool_id'), 'tool_snapshots', ['tool_id'], unique=False)
    op.drop_column('tool_snapshots', 'reddit_count')
    op.drop_column('tool_snapshots', 'stars')
    op.drop_column('tool_snapshots', 'devto_count')
    op.drop_column('tool_snapshots', 'hn_count')
    op.drop_column('tool_snapshots', 'date')
    op.drop_column('tool_snapshots', 'mentions')
    op.drop_column('tool_snapshots', 'forks')
    op.add_column('tools', sa.Column('mention_count', sa.Integer(), nullable=True))
    op.add_column('tools', sa.Column('sentiment_score', sa.Float(), nullable=True))
    op.add_column('tools', sa.Column('domain', sa.String(), nullable=True))
    op.add_column('tools', sa.Column('github_stars', sa.Integer(), nullable=True))
    op.add_column('tools', sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'last_updated')
    op.drop_column('tools', 'github_stars')
    op.drop_column('tools', 'domain')
    op.drop_column('tools', 'sentiment_score')
    op.drop_column('tools', 'mention_count')
    op.add_column('tool_snapshots', sa.Column('forks', sa.INTEGER(), nullable=True))
    op.add_column('tool_snapshots', sa.Column('mentions', sa.INTEGER(), nullable=True))
    op.add_column('tool_snapshots', sa.Column('date', sa.DATE(), nullable=False))
    op.add_column('tool_snapshots', sa.Column('hn_count', sa.INTEGER(), nullable=True))
    op.add_column('tool_snapshots', sa.Column('devto_count', sa.INTEGER(), nullable=True))
    op.add_column('tool_snapshots', sa.Column('stars', sa.INTEGER(), nullable=True))
    op.add_column('tool_snapshots', sa.Column('reddit_count', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_tool_snapshots_tool_id'), table_name='tool_snapshots')
    op.drop_index(op.f('ix_tool_snapshots_recorded_at'), table_name='tool_snapshots')
    op.create_unique_constraint('uq_tool_date', 'tool_snapshots', ['tool_id', 'date'])
    op.create_index('ix_tool_snapshots_id', 'tool_snapshots', ['id'], unique=False)
    op.drop_column('tool_snapshots', 'sentiment_score')
    op.drop_column('tool_snapshots', 'mention_count')
    op.drop_column('tool_snapshots', 'github_stars_delta')
    op.drop_column('tool_snapshots', 'recorded_at')
    # ### end Alembic commands ###
